### ISSUE TITLE
Depth generated image is all noise on rgb or infra obtained from Gazebo simulated d435

### ISSUE THREAD

**Issue by MarioCavero** [angli66/simsense#3]
Great work! Results look promising! I am facing an issue with data obtained by gazebo. I am simulating a realsense d435 and I want to have a noisy depth image simulating the real one. 

I have obtained 2 rgbs from 2 cameras 5cm to each other, and also 2 infra images obtained from infra1 and infra2 of the same camera. 
Both output me the same result with simsense:
![output_simsense](https://github.com/user-attachments/assets/a00bb7a0-99cb-4718-be6c-976a7fcbbe21)
And inputting infras of the same camera:
![input_infra](https://github.com/user-attachments/assets/b52b5e3a-e60a-4e23-9abe-9b938274a4a3)
RGBS of 2 different cameras at 5cm. 
![input_rgbs](https://github.com/user-attachments/assets/ecb22d25-987e-44eb-88a1-bbedda13299d)

Any clue? I am using my custom 
```
    k_l = np.array([
        [1386.41, 0.0, 960.0],
        [0.0, 1386.41, 540.0],
        [0.0, 0.0, 1.0]
    ])
```
for the rgb and another custom for the infras.

**Comment by angli66** [comment]
Hi, to get reasonably good result you should use IR images simulated with active light pattern of D435. If you take a look at the test images simsense used, the scene has been exposed with IR light. Without active light it's hard for stereo matching to get correct depth, especially for inputs with flat texture like yours. If you are interested in how to simulate IR images with active light I recommend you take a look at [sapien](https://github.com/haosulab/SAPIEN).

**Comment by MarioCavero** [comment]
Thank you very much for the quick reply! I thought it would also be possible with just rgb images. Right now I do not want to migrate all my workflow to Sapien as I am using Gazebo. If I manage to solve my issue, I will definitely test Sapien with a similar workflow! If there is nothing else I can try, feel free to close the issue! Thanks again for your time @angli66
